#!/usr/bin/env python3
# _*_ coding: utf-8 _*_
"""
文件名称:demand_table_heading.py
功能描述:定义测试结果列名
创建日期:2025-08-05
作者:王洋
版本:v1.0
修改记录:
"""


class TableTitle:
    DEMAND_COLUMNS_OF_3E4WY = [
        'test_case',
        'demand_accuracy',
        'voltage',
        'angle',
        'current',
        'freq(Hz)',
        'wire_type',
        'demand_method',
        'interval',
        'update_rate',
        'demand_trigger',

        'std_p_sys_1st',
        'demand_p_sys_1st',
        'std_q_sys_1st',
        'demand_q_sys_1st',
        'std_s_sys_1st',
        'demand_s_sys_1st',
        'std_ia_sys_1st',
        'demand_ia_sys_1st',
        'std_ib_sys_1st',
        'demand_ib_sys_1st',
        'std_ic_sys_1st',
        'demand_ic_sys_1st',
        'std_in_sys_1st',
        'demand_in_sys_1st',
        'is_pass_1st',

        'std_p_sys_2nd',
        'demand_p_sys_2nd',
        'std_q_sys_2nd',
        'demand_q_sys_2nd',
        'std_s_sys_2nd',
        'demand_s_sys_2nd',
        'std_ia_sys_2nd',
        'demand_ia_sys_2nd',
        'std_ib_sys_2nd',
        'demand_ib_sys_2nd',
        'std_ic_sys_2nd',
        'demand_ic_sys_2nd',
        'std_in_sys_2nd',
        'demand_in_sys_2nd',
        'is_pass_2nd',

        'std_p_sys_3rd',
        'demand_p_sys_3rd',
        'std_q_sys_3rd',
        'demand_q_sys_3rd',
        'std_s_sys_3rd',
        'demand_s_sys_3rd',
        'std_ia_sys_3rd',
        'demand_ia_sys_3rd',
        'std_ib_sys_3rd',
        'demand_ib_sys_3rd',
        'std_ic_sys_3rd',
        'demand_ic_sys_3rd',
        'std_in_sys_3rd',
        'demand_in_sys_3rd',
        'is_pass_3rd',
    ]

    DEMAND_COLUMNS_OF_1E2W1P = [
        'test_case',
        'demand_accuracy',
        'voltage',
        'angle',
        'current',
        'freq(Hz)',
        'wire_type',
        'demand_method',
        'interval',
        'update_rate',
        'demand_trigger',

        'std_p_sys_1st',
        'demand_p_sys_1st',
        'std_q_sys_1st',
        'demand_q_sys_1st',
        'std_s_sys_1st',
        'demand_s_sys_1st',
        'std_ia_sys_1st',
        'demand_ia_sys_1st',
        'std_ib_sys_1st',
        'demand_ib_sys_1st',
        'std_ic_sys_1st',
        'demand_ic_sys_1st',
        'std_in_sys_1st',
        'demand_in_sys_1st',
        'is_pass_1st',

        'std_p_sys_2nd',
        'demand_p_sys_2nd',
        'std_q_sys_2nd',
        'demand_q_sys_2nd',
        'std_s_sys_2nd',
        'demand_s_sys_2nd',
        'std_ia_sys_2nd',
        'demand_ia_sys_2nd',
        'std_ib_sys_2nd',
        'demand_ib_sys_2nd',
        'std_ic_sys_2nd',
        'demand_ic_sys_2nd',
        'std_in_sys_2nd',
        'demand_in_sys_2nd',
        'is_pass_2nd',

        'std_p_sys_3rd',
        'demand_p_sys_3rd',
        'std_q_sys_3rd',
        'demand_q_sys_3rd',
        'std_s_sys_3rd',
        'demand_s_sys_3rd',
        'std_ia_sys_3rd',
        'demand_ia_sys_3rd',
        'std_ib_sys_3rd',
        'demand_ib_sys_3rd',
        'std_ic_sys_3rd',
        'demand_ic_sys_3rd',
        'std_in_sys_3rd',
        'demand_in_sys_3rd',
        'is_pass_3rd',
    ]

    DEMAND_COLUMNS_OF_2E3W1P = [
        'test_case',
        'demand_accuracy',
        'voltage',
        'angle',
        'current',
        'freq(Hz)',
        'wire_type',
        'demand_method',
        'interval',
        'update_rate',
        'demand_trigger',

        'std_p_sys_1st',
        'demand_p_sys_1st',
        'std_q_sys_1st',
        'demand_q_sys_1st',
        'std_s_sys_1st',
        'demand_s_sys_1st',
        'std_ia_sys_1st',
        'demand_ia_sys_1st',
        'std_ib_sys_1st',
        'demand_ib_sys_1st',
        'std_ic_sys_1st',
        'demand_ic_sys_1st',
        'std_in_sys_1st',
        'demand_in_sys_1st',
        'is_pass_1st',

        'std_p_sys_2nd',
        'demand_p_sys_2nd',
        'std_q_sys_2nd',
        'demand_q_sys_2nd',
        'std_s_sys_2nd',
        'demand_s_sys_2nd',
        'std_ia_sys_2nd',
        'demand_ia_sys_2nd',
        'std_ib_sys_2nd',
        'demand_ib_sys_2nd',
        'std_ic_sys_2nd',
        'demand_ic_sys_2nd',
        'std_in_sys_2nd',
        'demand_in_sys_2nd',
        'is_pass_2nd',

        'std_p_sys_3rd',
        'demand_p_sys_3rd',
        'std_q_sys_3rd',
        'demand_q_sys_3rd',
        'std_s_sys_3rd',
        'demand_s_sys_3rd',
        'std_ia_sys_3rd',
        'demand_ia_sys_3rd',
        'std_ib_sys_3rd',
        'demand_ib_sys_3rd',
        'std_ic_sys_3rd',
        'demand_ic_sys_3rd',
        'std_in_sys_3rd',
        'demand_in_sys_3rd',
        'is_pass_3rd',
    ]

    DEMAND_COLUMNS_OF_2E3WN = [
        'test_case',
        'demand_accuracy',
        'voltage',
        'angle',
        'current',
        'freq(Hz)',
        'wire_type',
        'demand_method',
        'interval',
        'update_rate',
        'demand_trigger',

        'std_p_sys_1st',
        'demand_p_sys_1st',
        'std_q_sys_1st',
        'demand_q_sys_1st',
        'std_s_sys_1st',
        'demand_s_sys_1st',
        'std_ia_sys_1st',
        'demand_ia_sys_1st',
        'std_ib_sys_1st',
        'demand_ib_sys_1st',
        'std_ic_sys_1st',
        'demand_ic_sys_1st',
        'std_in_sys_1st',
        'demand_in_sys_1st',
        'is_pass_1st',

        'std_p_sys_2nd',
        'demand_p_sys_2nd',
        'std_q_sys_2nd',
        'demand_q_sys_2nd',
        'std_s_sys_2nd',
        'demand_s_sys_2nd',
        'std_ia_sys_2nd',
        'demand_ia_sys_2nd',
        'std_ib_sys_2nd',
        'demand_ib_sys_2nd',
        'std_ic_sys_2nd',
        'demand_ic_sys_2nd',
        'std_in_sys_2nd',
        'demand_in_sys_2nd',
        'is_pass_2nd',

        'std_p_sys_3rd',
        'demand_p_sys_3rd',
        'std_q_sys_3rd',
        'demand_q_sys_3rd',
        'std_s_sys_3rd',
        'demand_s_sys_3rd',
        'std_ia_sys_3rd',
        'demand_ia_sys_3rd',
        'std_ib_sys_3rd',
        'demand_ib_sys_3rd',
        'std_ic_sys_3rd',
        'demand_ic_sys_3rd',
        'std_in_sys_3rd',
        'demand_in_sys_3rd',
        'is_pass_3rd',
    ]

    DEMAND_COLUMNS_OF_2E3WD = [
        'test_case',
        'demand_accuracy',
        'voltage',
        'angle',
        'current',
        'freq(Hz)',
        'wire_type',
        'demand_method',
        'interval',
        'update_rate',
        'demand_trigger',

        'std_p_sys_1st',
        'demand_p_sys_1st',
        'std_q_sys_1st',
        'demand_q_sys_1st',
        'std_s_sys_1st',
        'demand_s_sys_1st',
        'std_ia_sys_1st',
        'demand_ia_sys_1st',
        'std_ib_sys_1st',
        'demand_ib_sys_1st',
        'std_ic_sys_1st',
        'demand_ic_sys_1st',
        'std_in_sys_1st',
        'demand_in_sys_1st',
        'is_pass_1st',

        'std_p_sys_2nd',
        'demand_p_sys_2nd',
        'std_q_sys_2nd',
        'demand_q_sys_2nd',
        'std_s_sys_2nd',
        'demand_s_sys_2nd',
        'std_ia_sys_2nd',
        'demand_ia_sys_2nd',
        'std_ib_sys_2nd',
        'demand_ib_sys_2nd',
        'std_ic_sys_2nd',
        'demand_ic_sys_2nd',
        'std_in_sys_2nd',
        'demand_in_sys_2nd',
        'is_pass_2nd',

        'std_p_sys_3rd',
        'demand_p_sys_3rd',
        'std_q_sys_3rd',
        'demand_q_sys_3rd',
        'std_s_sys_3rd',
        'demand_s_sys_3rd',
        'std_ia_sys_3rd',
        'demand_ia_sys_3rd',
        'std_ib_sys_3rd',
        'demand_ib_sys_3rd',
        'std_ic_sys_3rd',
        'demand_ic_sys_3rd',
        'std_in_sys_3rd',
        'demand_in_sys_3rd',
        'is_pass_3rd',
    ]

    DEMAND_COLUMNS_OF_3E4WD = [
        'test_case',
        'demand_accuracy',
        'voltage',
        'angle',
        'current',
        'freq(Hz)',
        'wire_type',
        'demand_method',
        'interval',
        'update_rate',
        'demand_trigger',

        'std_p_sys_1st',
        'demand_p_sys_1st',
        'std_q_sys_1st',
        'demand_q_sys_1st',
        'std_s_sys_1st',
        'demand_s_sys_1st',
        'std_ia_sys_1st',
        'demand_ia_sys_1st',
        'std_ib_sys_1st',
        'demand_ib_sys_1st',
        'std_ic_sys_1st',
        'demand_ic_sys_1st',
        'std_in_sys_1st',
        'demand_in_sys_1st',
        'is_pass_1st',

        'std_p_sys_2nd',
        'demand_p_sys_2nd',
        'std_q_sys_2nd',
        'demand_q_sys_2nd',
        'std_s_sys_2nd',
        'demand_s_sys_2nd',
        'std_ia_sys_2nd',
        'demand_ia_sys_2nd',
        'std_ib_sys_2nd',
        'demand_ib_sys_2nd',
        'std_ic_sys_2nd',
        'demand_ic_sys_2nd',
        'std_in_sys_2nd',
        'demand_in_sys_2nd',
        'is_pass_2nd',

        'std_p_sys_3rd',
        'demand_p_sys_3rd',
        'std_q_sys_3rd',
        'demand_q_sys_3rd',
        'std_s_sys_3rd',
        'demand_s_sys_3rd',
        'std_ia_sys_3rd',
        'demand_ia_sys_3rd',
        'std_ib_sys_3rd',
        'demand_ib_sys_3rd',
        'std_ic_sys_3rd',
        'demand_ic_sys_3rd',
        'std_in_sys_3rd',
        'demand_in_sys_3rd',
        'is_pass_3rd',
    ]



if __name__ == '__main__':
    out_name = [i for i in TableTitle.DEMAND_COLUMNS_OF_3E4WY]
    print(out_name)
