gateway:
  url: https://192.168.2.9/#/login
  username: admin
  password: Admin@110001
aws_iot:
  enable: true
  client_id: AHI260110001
  url: apbmxreennh9b-ats.iot.cn-northwest-1.amazonaws.com.cn
  topic: test/topic/aws
  interval: 30 seconds
  cert_file: Protocols/IoT/AWS_IoT/certs/client.pem
  key_file: Protocols/IoT/AWS_IoT/certs/key.pem
  ca_file: Protocols/IoT/AWS_IoT/certs/AmazonRootCA1.pem
  sub_cert_file: Protocols/IoT/AWS_IoT/certs/29e287f92d07dc357838878febdac0cfc1d046b2abf81c715d2f42be4a2477c6-certificate.pem.crt
  sub_key_file: Protocols/IoT/AWS_IoT/certs/29e287f92d07dc357838878febdac0cfc1d046b2abf81c715d2f42be4a2477c6-private.pem.key
  expected_devices:
  - AcuRev2100
  - AcuRev4100
  - Acurev1300
  - Acuvim3
  - AcuvimIIR
  - AcuvimIIW
