[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# pytest-playwright default browser
addopts =
    --browser chromium
    --html=reports/report.html
    --self-contained-html
    -v

# Markers
markers =
    smoke: smoke tests
    regression: regression tests
    login: login related tests
