mapping = {
    # === From 200ms sheet ===
    "FREQ_Hz":              ("0x2114", "float",  2, "System Frequency"),
    "VLN_a_V":             ("0x2116", "float",  2, "Phase A Line-to-Neutral Voltage"),
    "VLN_b_V":             ("0x2118", "float",  2, "Phase B Line-to-Neutral Voltage"),
    "VLN_c_V":             ("0x211A", "float",  2, "Phase C Line-to-Neutral Voltage"),
    "VLN_avg_V":           ("0x211C", "float",  2, "Average Line-to-Neutral Voltage"),
    "VLL_ab_V":            ("0x211E", "float",  2, "Phase AB Line-to-Line Voltage"),
    "VLL_bc_V":            ("0x2120", "float",  2, "Phase BC Line-to-Line Voltage"),
    "VLL_ca_V":            ("0x2122", "float",  2, "Phase CA Line-to-Line Voltage"),
    "VLL_avg_V":           ("0x2124", "float",  2, "Average Line-to-Line Voltage"),
    "I_a_A":               ("0x2126", "float",  2, "Phase A Current"),
    "I_b_A":               ("0x2128", "float",  2, "Phase B Current"),
    "I_c_A":               ("0x212A", "float",  2, "Phase C Current"),
    "I_n_A":               ("0x212C", "float",  2, "Phase N Current"),
    "I_avg_A":             ("0x212E", "float",  2, "Average Current"),
    "P_a_kW":              ("0x2130", "float",  2, "Phase A Active Power"),
    "P_b_kW":              ("0x2132", "float",  2, "Phase B Active Power"),
    "P_c_kW":              ("0x2134", "float",  2, "Phase C Active Power"),
    "P_kW":                ("0x2136", "float",  2, "System Active Power"),
    "Q_a_kvar":            ("0x2138", "float",  2, "Phase A Reactive Power"),
    "Q_b_kvar":            ("0x213A", "float",  2, "Phase B Reactive Power"),
    "Q_c_kvar":            ("0x213C", "float",  2, "Phase C Reactive Power"),
    "Q_kvar":              ("0x213E", "float",  2, "System Reactive Power"),
    "S_a_kVA":             ("0x2140", "float",  2, "Phase A Apparent Power"),
    "S_b_kVA":             ("0x2142", "float",  2, "Phase B Apparent Power"),
    "S_c_kVA":             ("0x2144", "float",  2, "Phase C Apparent Power"),
    "S_kVA":               ("0x2146", "float",  2, "System Apparent Power"),
    "PF_a":                ("0x2150", "float",  2, "Phase A Power Factor"),
    "PF_b":                ("0x2152", "float",  2, "Phase B Power Factor"),
    "PF_c":                ("0x2154", "float",  2, "Phase C Power Factor"),
    "PF":                  ("0x2156", "float",  2, "System Power Factor"),
    "LEAD_PF_a":           ("0x2158", "float",  2, "Phase A Leading Power Factor"),
    "LEAD_PF_b":           ("0x215A", "float",  2, "Phase B Leading Power Factor"),
    "LEAD_PF_c":           ("0x215C", "float",  2, "Phase C Leading Power Factor"),
    "LEAD_PF":             ("0x215E", "float",  2, "System Leading Power Factor"),
    "LAG_PF_a":            ("0x2160", "float",  2, "Phase A Lagging Power Factor"),
    "LAG_PF_b":            ("0x2162", "float",  2, "Phase B Lagging Power Factor"),
    "LAG_PF_c":            ("0x2164", "float",  2, "Phase C Lagging Power Factor"),
    "LAG_PF":              ("0x2166", "float",  2, "System Lagging Power Factor"),
    "ANG_VLN_a":           ("0x2168", "float",  2, "Phase A L-N Voltage Phase Angle"),
    "ANG_VLN_b":           ("0x216A", "float",  2, "Phase B L-N Voltage Phase Angle"),
    "ANG_VLN_c":           ("0x216C", "float",  2, "Phase C L-N Voltage Phase Angle"),
    "ANG_VLL_ab":          ("0x216E", "float",  2, "Phase AB L-L Voltage Phase Angle"),
    "ANG_VLL_bc":          ("0x2170", "float",  2, "Phase BC L-L Voltage Phase Angle"),
    "ANG_VLL_ca":          ("0x2172", "float",  2, "Phase CA L-L Voltage Phase Angle"),
    "ANG_I_a":             ("0x2174", "float",  2, "Phase A Current Phase Angle"),
    "ANG_I_b":             ("0x2176", "float",  2, "Phase B Current Phase Angle"),
    "ANG_I_c":             ("0x2178", "float",  2, "Phase C Current Phase Angle"),
    # Voltage Sequence
    "MAG_SEQ_POS_V":       ("0x217A", "float",  2, "Voltage Positive Sequence Magnitude"),
    "MAG_SEQ_ZERO_V":      ("0x217C", "float",  2, "Voltage Zero Sequence Magnitude"),
    "MAG_SEQ_NEG_V":       ("0x217E", "float",  2, "Voltage Negative Sequence Magnitude"),
    "SEQ_ZERO_RATIO_V_%":  ("0x2180", "float",  2, "Voltage Zero Sequence Ratio"),
    "UNBL_V_%":            ("0x2182", "float",  2, "Voltage Unbalance Factor"),
    # Current Sequence
    "MAG_SEQ_POS_I":       ("0x2184", "float",  2, "Current Positive Sequence Magnitude"),
    "MAG_SEQ_ZERO_I":      ("0x2186", "float",  2, "Current Zero Sequence Magnitude"),
    "MAG_SEQ_NEG_I":       ("0x2188", "float",  2, "Current Negative Sequence Magnitude"),
    "SEQ_ZERO_RATIO_I_%":  ("0x218A", "float",  2, "Current Zero Sequence Ratio"),
    "UNBL_I_%":            ("0x218C", "float",  2, "Current Unbalance Factor"),
    # Sequence Angles
    "ANG_SEQ_POS_V":       ("0x218E", "float",  2, "Voltage Positive Sequence Angle"),
    "ANG_SEQ_ZERO_V":      ("0x2190", "float",  2, "Voltage Zero Sequence Angle"),
    "ANG_SEQ_NEG_V":       ("0x2192", "float",  2, "Voltage Negative Sequence Angle"),
    "ANG_SEQ_POS_I":       ("0x2194", "float",  2, "Current Positive Sequence Angle"),
    "ANG_SEQ_ZERO_I":      ("0x2196", "float",  2, "Current Zero Sequence Angle"),
    "ANG_SEQ_NEG_I":       ("0x2198", "float",  2, "Current Negative Sequence Angle"),
    # Voltage THD / OTHD / ETHD / CF
    "THD_V_a_%":           ("0x219A", "float",  2, "Phase A Voltage THD"),
    "THD_V_b_%":           ("0x219C", "float",  2, "Phase B Voltage THD"),
    "THD_V_c_%":           ("0x219E", "float",  2, "Phase C Voltage THD"),
    "OTHD_V_a_%":          ("0x21A0", "float",  2, "Phase A Voltage THD Odd"),
    "OTHD_V_b_%":          ("0x21A2", "float",  2, "Phase B Voltage THD Odd"),
    "OTHD_V_c_%":          ("0x21A4", "float",  2, "Phase C Voltage THD Odd"),
    "ETHD_V_a_%":          ("0x21A6", "float",  2, "Phase A Voltage THD Even"),
    "ETHD_V_b_%":          ("0x21A8", "float",  2, "Phase B Voltage THD Even"),
    "ETHD_V_c_%":          ("0x21AA", "float",  2, "Phase C Voltage THD Even"),
    "CF_V_a_%":            ("0x21AC", "float",  2, "Phase A Voltage Crest Factor"),
    "CF_V_b_%":            ("0x21AE", "float",  2, "Phase B Voltage Crest Factor"),
    "CF_V_c_%":            ("0x21B0", "float",  2, "Phase C Voltage Crest Factor"),
    # Current THD / OTHD / ETHD / TDD / CF / KF
    "THD_I_a_%":           ("0x21B2", "float",  2, "Phase A Current THD"),
    "THD_I_b_%":           ("0x21B4", "float",  2, "Phase B Current THD"),
    "THD_I_c_%":           ("0x21B6", "float",  2, "Phase C Current THD"),
    "THD_I_n_%":           ("0x21B8", "float",  2, "Phase N Current THD"),
    "OTHD_I_a_%":          ("0x21BA", "float",  2, "Phase A Current THD Odd"),
    "OTHD_I_b_%":          ("0x21BC", "float",  2, "Phase B Current THD Odd"),
    "OTHD_I_c_%":          ("0x21BE", "float",  2, "Phase C Current THD Odd"),
    "OTHD_I_n_%":          ("0x21C0", "float",  2, "Phase N Current THD Odd"),
    "ETHD_I_a_%":          ("0x21C2", "float",  2, "Phase A Current THD Even"),
    "ETHD_I_b_%":          ("0x21C4", "float",  2, "Phase B Current THD Even"),
    "ETHD_I_c_%":          ("0x21C6", "float",  2, "Phase C Current THD Even"),
    "ETHD_I_n_%":          ("0x21C8", "float",  2, "Phase N Current THD Even"),
    "TDD_I_a_%":           ("0x21CA", "float",  2, "Phase A Current TDD"),
    "TDD_I_b_%":           ("0x21CC", "float",  2, "Phase B Current TDD"),
    "TDD_I_c_%":           ("0x21CE", "float",  2, "Phase C Current TDD"),
    "TDD_I_n_%":           ("0x21D0", "float",  2, "Phase N Current TDD"),
    "CF_I_a_%":            ("0x21D2", "float",  2, "Phase A Current Crest-Factor"),
    "CF_I_b_%":            ("0x21D4", "float",  2, "Phase B Current Crest-Factor"),
    "CF_I_c_%":            ("0x21D6", "float",  2, "Phase C Current Crest-Factor"),
    "CF_I_n_%":            ("0x21D8", "float",  2, "Phase N Current Crest-Factor"),
    "KF_I_a_%":            ("0x21DA", "float",  2, "Phase A Current K-Factor"),
    "KF_I_b_%":            ("0x21DC", "float",  2, "Phase B Current K-Factor"),
    "KF_I_c_%":            ("0x21DE", "float",  2, "Phase C Current K-Factor"),
    "KF_I_n_%":            ("0x21E0", "float",  2, "Phase N Current K-Factor"),
    # Voltage Flicker
    "FLICK_V_a":           ("0x21E2", "float",  2, "Phase A Voltage Flicker"),
    "FLICK_V_b":           ("0x21E4", "float",  2, "Phase B Voltage Flicker"),
    "FLICK_V_c":           ("0x21E6", "float",  2, "Phase C Voltage Flicker"),

    # === From Demand sheet ===
    "DMD_I_a_A":           ("0x6100", "float",  2, "Phase A Current Demand"),
    "DMD_I_b_A":           ("0x6102", "float",  2, "Phase B Current Demand"),
    "DMD_I_c_A":           ("0x6104", "float",  2, "Phase C Current Demand"),
    "DMD_I_avg_A":         ("0x6106", "float",  2, "Average Current Demand"),
    "DMD_P_a_kW":          ("0x6198", "float",  2, "Phase A Active Power Demand-Total"),
    "DMD_P_b_kW":          ("0x619A", "float",  2, "Phase B Active Power Demand-Total"),
    "DMD_P_c_kW":          ("0x619C", "float",  2, "Phase C Active Power Demand-Total"),
    "DMD_P_kW":            ("0x619E", "float",  2, "System Active Power Demand-Total"),
    "DMD_Q_a_kvar":        ("0x61A0", "float",  2, "Phase A Reactive Power Demand-Total"),
    "DMD_Q_b_kvar":        ("0x61A2", "float",  2, "Phase B Reactive Power Demand-Total"),
    "DMD_Q_c_kvar":        ("0x61A4", "float",  2, "Phase C Reactive Power Demand-Total"),
    "DMD_Q_kvar":          ("0x61A6", "float",  2, "System Reactive Power Demand-Total"),
    "DMD_S_a_kVA":         ("0x61A8", "float",  2, "Phase A Apparent Power Demand"),
    "DMD_S_b_kVA":         ("0x61AA", "float",  2, "Phase B Apparent Power Demand"),
    "DMD_S_c_kVA":         ("0x61AC", "float",  2, "Phase C Apparent Power Demand"),
    "DMD_S_kVA":           ("0x61AE", "float",  2, "System Apparent Power Demand"),

    # === From Energy sheet ===
    # Import
    "EP_IMP_a_kWh":        ("0x65C0", "Double", 4, "Accumulative Phase A Active Energy-Import"),
    "EP_IMP_b_kWh":        ("0x65C4", "Double", 4, "Accumulative Phase B Active Energy-Import"),
    "EP_IMP_c_kWh":        ("0x65C8", "Double", 4, "Accumulative Phase C Active Energy-Import"),
    "EP_IMP_kWh":          ("0x65CC", "Double", 4, "Accumulative System Active Energy-Import"),
    "EQ_IMP_a_kvarh":      ("0x65D0", "Double", 4, "Accumulative Phase A Reactive Energy-Import"),
    "EQ_IMP_b_kvarh":      ("0x65D4", "Double", 4, "Accumulative Phase B Reactive Energy-Import"),
    "EQ_IMP_c_kvarh":      ("0x65D8", "Double", 4, "Accumulative Phase C Reactive Energy-Import"),
    "EQ_IMP_kvarh":        ("0x65DC", "Double", 4, "Accumulative System Reactive Energy-Import"),
    # Export
    "EP_EXP_a_kWh":        ("0x65E0", "Double", 4, "Accumulative Phase A Active Energy-Export"),
    "EP_EXP_b_kWh":        ("0x65E4", "Double", 4, "Accumulative Phase B Active Energy-Export"),
    "EP_EXP_c_kWh":        ("0x65E8", "Double", 4, "Accumulative Phase C Active Energy-Export"),
    "EP_EXP_kWh":          ("0x65EC", "Double", 4, "Accumulative System Active Energy-Export"),
    "EQ_EXP_a_kvarh":      ("0x65F0", "Double", 4, "Accumulative Phase A Reactive Energy-Export"),
    "EQ_EXP_b_kvarh":      ("0x65F4", "Double", 4, "Accumulative Phase B Reactive Energy-Export"),
    "EQ_EXP_c_kvarh":      ("0x65F8", "Double", 4, "Accumulative Phase C Reactive Energy-Export"),
    "EQ_EXP_kvarh":        ("0x65FC", "Double", 4, "Accumulative System Reactive Energy-Export"),
    # Net
    "EP_NET_a_kWh":        ("0x6600", "Double", 4, "Accumulative Phase A Active Energy-Net"),
    "EP_NET_b_kWh":        ("0x6604", "Double", 4, "Accumulative Phase B Active Energy-Net"),
    "EP_NET_c_kWh":        ("0x6608", "Double", 4, "Accumulative Phase C Active Energy-Net"),
    "EP_NET_kWh":          ("0x660C", "Double", 4, "Accumulative System Active Energy-Net"),
    "EQ_NET_a_kvarh":      ("0x6610", "Double", 4, "Accumulative Phase A Reactive Energy-Net"),
    "EQ_NET_b_kvarh":      ("0x6614", "Double", 4, "Accumulative Phase B Reactive Energy-Net"),
    "EQ_NET_c_kvarh":      ("0x6618", "Double", 4, "Accumulative Phase C Reactive Energy-Net"),
    "EQ_NET_kvarh":        ("0x661C", "Double", 4, "Accumulative System Reactive Energy-Net"),
    # Total
    "EP_TOTAL_a_kWh":      ("0x6620", "Double", 4, "Accumulative Phase A Active Energy-Total"),
    "EP_TOTAL_b_kWh":      ("0x6624", "Double", 4, "Accumulative Phase B Active Energy-Total"),
    "EP_TOTAL_c_kWh":      ("0x6628", "Double", 4, "Accumulative Phase C Active Energy-Total"),
    "EP_TOTAL_kWh":        ("0x662C", "Double", 4, "Accumulative System Active Energy-Total"),
    "EQ_TOTAL_a_kvarh":    ("0x6630", "Double", 4, "Accumulative Phase A Reactive Energy-Total"),
    "EQ_TOTAL_b_kvarh":    ("0x6634", "Double", 4, "Accumulative Phase B Reactive Energy-Total"),
    "EQ_TOTAL_c_kvarh":    ("0x6638", "Double", 4, "Accumulative Phase C Reactive Energy-Total"),
    "EQ_TOTAL_kvarh":      ("0x663C", "Double", 4, "Accumulative System Reactive Energy-Total"),
    # Apparent Energy
    "ES_a_kVAh":           ("0x6640", "Double", 4, "Accumulative Phase A Apparent Energy"),
    "ES_b_kVAh":           ("0x6644", "Double", 4, "Accumulative Phase B Apparent Energy"),
    "ES_c_kVAh":           ("0x6648", "Double", 4, "Accumulative Phase C Apparent Energy"),
    "ES_kVAh":             ("0x664C", "Double", 4, "Accumulative System Apparent Energy"),
}

print(f"Total parameters mapped: {len(mapping)}")
print()
print("=" * 100)
print(f"{'EPICS PV (AcuVIM3-)':<30} {'Hex Addr':<10} {'DType':<8} {'Regs':<5} Description")
print("=" * 100)
for key, (addr, dtype, regs, desc) in mapping.items():
    pv = "AcuVIM3-" + key
    print(f"{pv:<38} {addr:<10} {dtype:<8} {regs:<5} {desc}")
